name: Build Image And Update GitOps Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application source
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitops-demo-app:${IMAGE_TAG} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitops-demo-app:${IMAGE_TAG}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO_USERNAME }}/gitops-manifests.git
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops-manifests

      - name: Update deployment image and version
        run: |
          cd gitops-manifests
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-demo-app:${IMAGE_TAG}|g" kubernetes/deployment.yaml
          sed -i "s|value: \".*\"|value: \"${IMAGE_TAG}\"|g" kubernetes/deployment.yaml

      - name: Commit and push GitOps changes
        run: |
          cd gitops-manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add kubernetes/deployment.yaml
          git commit -m "Update image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin HEAD:main
